version: '3.8'
services:
  api_rotas:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '4910:4910'
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./
