version: '3.8'
services:
  scrapper:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3290:3290'
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./
